version: '3.9'

services:
  mysql:
    image: mysql:8.0
    command: --local-infile=1
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: app_data
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  airflow:
    build: ./airflow
    container_name: airflow
    command: standalone
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./datasets:/opt/airflow/datasets
      - airflow_data:/home/airflow/airflow
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongo


  dash:
    build: ./dash_app
    container_name: dash_app
    ports:
      - "8050:8050"
    depends_on:
      - mysql
      - mongo

volumes:
  mysql_data:
  mongo_data:
  airflow_data: